const translations = {
    en: {
        why: "Why this app?",
        how: "How to use?",
        privacy: "Privacy & Permissions.",
        contact: "Contact & Requests.",
        donate: "Donate",
        tagline: "An autonomous safety net for you and your pets.",
        downloadBtn: "Get it on Google Play",
        coreIdea: "The Core Idea: Independence, Secured",
        para1: "Living alone comes with a quiet, persistent worry: What if something happened to me? How long would it be before someone knew? For those who cherish their independence but acknowledge the reality of living solo, this question deserves a simple, reliable, and private answer.",
        para2: "I'm OK is your personal, automated safety net. It is an honest tool for peace of mind. It is not a tracker; it respects your privacy while discreetly watching over your well-being. It is designed for the independent spirit who wants to relieve their loved ones of worry, without sacrificing their autonomy.",
        para3: "According to a schedule you set, the app sends you a single, discreet notification. A simple tap on the \"I'm OK\" button is all it takes to confirm your well-being. If that confirmation doesn't happen, and only then, your personal, pre-defined emergency plan is set in motion.",
        personalStory: "A Personal Story: The Reason Why",
        para4: "\"I developed this app from a personal need. As someone who lives alone and has limited social contact, my biggest concern wasn't for myself, but for my little dog, Mara. She is the reason I go outside, the reason this app exists: to ensure she would never be left alone.",
        para5: "I am one of those people you sometimes read about in the newspaper, found in their home months later. Whether I'm found in that state isn't my problem at that moment. But ensuring my little dog is rescued, is. This app is the answer to that question. It is my way of giving back to her. She keeps me alive, and I am building a system that guarantees her safety.",
        para6: "It's a tool built to provide a safety net, not just for me, but for anyone in a similar situation. It's a way to ensure that in an emergency, help is on the way for those who depend on us, whether they have two legs or four.\"",
	bothMara: "\"Both Mara and I could really use some support. If you're happy with this free app, consider offering a coffee or a bone...\"",
        howItWorks: "How It Works: The Patient, Three-Stage System",
        philosophy: "The philosophy of I'm OK is reliability and the avoidance of false alarms. It is not built for speed, but for certainty.",
        dailyCheckin: "The Check-in.",
        dailyCheckinText: "According to a schedule you set, you receive a notification. One tap on \"I'm OK\" is enough. The app then disappears back into the background.",
        audibleReminder: "The Audible Reminder.",
        audibleReminderText: "Did you miss the first notification? Don't worry. The app knows that people forget their phones. After a while, it will only produce an audible reminder every half hour. No extra visual notifications to cause alarm. This is a built-in buffer, giving you hours to respond to a simple oversight.",
        emergencyPlan: "The Emergency Plan in Action.",
        emergencyPlanText: "Only after a long period of unresponsiveness, a duration you control, does the emergency plan activate.",
        familyFriends: "For Family and Friends: Shared Peace of Mind",
        para7: "Are you a son, daughter, or grandchild worried about a parent or grandparent who lives alone? \"I'm OK\" provides a non-intrusive way to ensure they are safe. It offers you a feeling of security without disturbing their cherished independence. By helping them set up the app, you will know that a reliable system is in place, watching over them when you can't.",
        howDoesWork: "How does the I'm OK app work?",
        howDoesWorkText: "The I'm OK app is designed to ensure your safety by checking in with you according to a schedule you set. If you do not confirm in time, the app can automatically inform your contacts.",
        settingUpCheckin: "Setting up the Check-in",
        setupText: "Go to the \"Check-in\" and \"Info & Plan\" pages to configure the app. Here you can set the following:",
        checkinTime: "Check-in Schedule:",
        checkinTimeText: "On the \"Check-in\" page, you can set the interval, time range, and active days for your check-in notifications.",
        yourName: "Your name:",
        yourNameText: "Enter your name in the \"Info & Plan\" page. This name is used in the messages sent to your contacts.",
        emergencyPlanSetup: "Emergency Plan:",
        emergencyPlanSetupText: "Create an emergency plan in the \"Info & Plan\" page. This plan is included in the messages sent to your contacts.",
        settingUpActions: "Setting up Alerts",
        actionsText: "In the \"Alerts\" page, you can define who should receive a message if you do not respond to the check-in. You can choose between SMS and email. Set the delay (in hours and minutes) after which the message should be sent. You can add multiple alerts.",
        smartApproach: "A Smart Approach to Setting Delays",
        smartApproachText: "The purpose of this app is to alert someone in a true emergency, not to send worrying messages unnecessarily. It is crucial to set your delays thoughtfully to build in a safety buffer. Give yourself enough time to confirm your status, even if you've forgotten your phone at home or are otherwise delayed.",
        layeredApproach: "Consider a layered approach to your emergency plan. For example:",
        firstDelay: "First delay (e.g., 4 hours after check-in):",
        firstDelayText: "Notify a close neighbor for a quick wellness check.",
        secondDelay: "Second delay (e.g., 6 hours):",
        secondDelayText: "Alert a family member who lives further away.",
        thirdDelay: "Third delay (e.g., 8 hours):",
        thirdDelayText: "Contact emergency services as a final step.",
        missedCheckin: "What happens if you miss a check-in?",
        missedCheckinText: "If you miss your daily check-in, the app's alert system is activated. The app will begin to play an audible reminder every hour and will continue to do so until you confirm that you are okay.",
        crucially: "Crucially, no alerts will be sent if you confirm your status before the delay of your first action has passed. The system is designed to give you ample time to respond and avoid false alarms.",
        confirmText: "If you do not confirm within the configured time, the app will proceed to execute your predefined alerts. Your contacts will then receive the messages you have prepared, including your emergency plan.",
        dataStorage: "Data Storage",
        dataStorageText: "All data you enter in the I'm OK app is stored exclusively locally on your device. The app does not require an internet connection for its core functionalities and does not send your personal data anywhere. The stored data includes:",
        settings: "Settings:",
        settingsText: "Your name, the check-in plan, your emergency plan, and the configured alerts (SMS/email) are stored locally.",
        statusInfo: "Status Information:",
        statusInfoText: "The app locally tracks when the last successful check-in was and if any notifications have been missed.",
        requiredPermissions: "Required Permissions",
        requiredPermissionsText: "To function correctly, the I'm OK app requires the following permissions:",
        notifications: "Notifications (POST_NOTIFICATIONS):",
        notificationsText: "Necessary to send you the daily check-in reminder.",
        alarms: "Alarms and Reminders (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Used to ensure the check-in notification is delivered at the exact set time, even if the device is inactive.",
        sms: "Send SMS messages (SEND_SMS):",
        smsText: "Allows the app to send an SMS on your behalf to your contacts if you miss a check-in.",
        readContacts: "Read contacts (READ_CONTACTS):",
        readContactsText: "Allows you to select a recipient for an action directly from your contact list. The app only reads the selected contact information and does not store it for other purposes.",
        foreground: "Foreground service (FOREGROUND_SERVICE):",
        foregroundText: "Ensures that the app can reliably perform actions (such as sending an SMS or email), even when the app is running in the background.",
        inAppPurchases: "In-app purchases (BILLING):",
        inAppPurchasesText: "Allows you to make donations to support the app's development.",
        preventPhone: "Prevent phone from sleeping (WAKE_LOCK):",
        preventPhoneText: "Ensures that the app can reliably perform alerts (like sending an SMS or email) without being interrupted by the device going to sleep.",
        runOnStartup: "Run on startup (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Allows the app to automatically reschedule your daily check-in after your device restarts.",
        internet: "Internet (INTERNET):",
        internetText: "Required for sending email alerts and for making voluntary donations through te app.",
        contactRequests: "Contact & Requests:",
        developedBy: "Developed by:",
        aspiesApps: "Aspie's Apps",
        feedback: "Questions or feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | With care for people and their pets.",
        whyThisApp: "Why this app?",
        howToUse: "How to use?",
        privacyPermissions: "Privacy & Permissions:",
        withCare: "With care for people and their pets.",
    },
    nl: {
        why: "Waarom deze app?",
        how: "Hoe te gebruiken?",
        privacy: "Privacy & Toestemmingen.",
        contact: "Contact & Verzoeken.",
        donate: "Doneer",
        tagline: "Een autonoom veiligheidssysteem voor jou en je huisdieren.",
        downloadBtn: "Download het op Google Play",
        coreIdea: "Het kernidee: Onafhankelijkheid, verzekerd",
        para1: "Alleen wonen brengt een stille, aanhoudende zorg met zich mee: \"Wat als er iets met me gebeurt? Hoe lang duurt het voordat iemand het weet?\" Voor degenen die hun onafhankelijkheid koesteren, maar de realiteit van alleen wonen erkennen, verdient deze vraag een eenvoudig, betrouwbaar en privé antwoord.",
        para2: "I'm OK is je persoonlijke, geautomatiseerde veiligheidssysteem. Het is een eerlijk hulpmiddel voor gemoedsrust. Het is geen tracker; het respecteert je privacy terwijl het discreet over je welzijn waakt. Het is ontworpen voor de onafhankelijke geest die zijn dierbaren van zorgen wil verlossen, zonder hun autonomie op te offeren.",
        para3: "Volgens een door jou ingesteld schema stuurt de app je een discrete notificatie. Een simpele tik op de \"I'm OK\"-knop is alles wat nodig is om je welzijn te bevestigen. Als die bevestiging uitblijft, en alleen dan, treden je persoonlijke, vooraf gedefinieerde noodwaarschuwingen in werking.",
        personalStory: "Een persoonlijk verhaal: Waarom",
        para4: "\"Ik heb deze app ontwikkeld uit persoonlijke behoefte. Als iemand die alleen woont en beperkt sociaal contact heeft, was mijn grootste zorg niet voor mijzelf, maar voor mijn hondje, Mara. Zij is de reden dat ik naar buiten kom, de reden dat deze app bestaat: om ervoor te zorgen dat ze nooit alleen zou worden achtergelaten.",
        para5: "Ik ben een van die mensen waar je soms over leest in de krant, maanden later in hun huis gevonden. Of ik in die toestand word gevonden, is op dat moment niet mijn probleem. Maar ervoor zorgen dat mijn hondje wordt gered, is dat wel. Deze app is het antwoord op die vraag. Het is mijn manier om iets terug te doen voor haar. Ze houdt me in leven, en ik bouw een systeem dat haar veiligheid garandeert.",
        para6: "Het is een hulpmiddel dat is gebouwd om een vangnet te bieden, niet alleen voor mij, maar voor iedereen in een vergelijkbare situatie. Het is een manier om ervoor te zorgen dat in een noodgeval hulp onderweg is voor degenen die van ons afhankelijk zijn, of ze nu twee benen hebben of vier.\"",
	bothMara: "\"Zowel Mara als ik kunnen wel wat steun gebruiken. Als je tevreden bent met deze gratis app, overweeg dan om een kopje koffie of een kluif aan te bieden...\"",
        howItWorks: "Hoe het werkt: Het geduldigde drietrapssysteem",
        philosophy: "De filosofie van I'm OK is betrouwbaarheid en het vermijden van valse alarmen. Het is niet gebouwd voor snelheid, maar voor zekerheid.",
        dailyCheckin: "De Check-in.",
        dailyCheckinText: "Volgens een door u ingesteld schema ontvangt u een melding. Een tik op \"I'm OK\" is genoeg. De app verdwijnt dan terug op de achtergrond.",
        audibleReminder: "De hoorbare herinnering.",
        audibleReminderText: "Heb je de eerste notificatie gemist? Geen zorgen. De app weet dat mensen hun telefoon vergeten. Na een tijdje produceert het elke dertig minuten een hoorbare herinnering. Geen extra visuele meldingen die alarm veroorzaken. Dit is een ingebouwde buffer die je uren de tijd geeft om op een eenvoudig verzuim te reageren.",
        emergencyPlan: "De Noodwaarschuwingen in Actie.",
        emergencyPlanText: "Alleen na een lange periode van niet-reageren, een duur die je zelf bepaalt, wordt het noodwaarschuwingssysteem geactiveerd.",
        familyFriends: "Voor familie en vrienden: Gedeelde gemoedsrust",
        para7: "Ben je een zoon, dochter of kleinkind die zich zorgen maakt over een ouder of grootouder die alleen woont? \"I'm OK\" biedt een niet-opdringerige manier om ervoor te zorgen dat ze veilig zijn. Het biedt je een gevoel van veiligheid zonder hun gekoesterde onafhankelijkheid te verstoren. Door hen te helpen de app in te stellen, weet je dat een betrouwbaar systeem is dat over hen waakt wanneer jij dat niet kunt.",
        howDoesWork: "Hoe werkt de I'm OK app?",
        howDoesWorkText: "De I'm OK app is ontworpen om je veiligheid te garanderen door bij je in te checken volgens een flexibel schema dat je zelf instelt. Als je niet op tijd bevestigt, kan de app je contacten automatisch informeren.",
        settingUpCheckin: "Je vangnet instellen",
        setupText: "Ga naar de pagina's \"Check-in\" en \"Info & Plan\" om de app in te stellen. Hier kun je het volgende instellen:",
        checkinTime: "Check-in Schema:",
        checkinTimeText: "Op de \"Check-in\"-pagina kun je kiezen hoe vaak je een notificatie wilt ontvangen. Stel het interval, het tijdvenster (bv. van 9u tot 22u) en de dagen van de week waarop het schema actief is in.",
        yourName: "Jouw naam:",
        yourNameText: "Voerop de \"Info & Plan\"-pagina je naam in. Deze naam wordt gebruikt in de berichten die naar je contacten worden gestuurd.",
        emergencyPlanSetup: "Noodplan:",
        emergencyPlanSetupText: "Maak ook op de \"Info & Plan\"-pagina een noodplan aan. Dit plan wordt opgenomen in de berichten die naar je contacten worden verstuurd.",
        settingUpActions: "Alerts instellen",
        actionsText: "Op de \"Alerts\"-pagina kun je definiëren wie een bericht moet ontvangen als je niet reageert op de check-in. Je kunt kiezen tussen SMS en e-mail. Stel de wachttijd (in uren en minuten) in waarna het bericht moet worden verzonden. Je kunt meerdere alerts toevoegen.",
        smartApproach: "Een slimme aanpak voor het instellen van wachttijden",
        smartApproachText: "Het doel van deze app is om iemand te waarschuwen in een echte noodsituatie, niet om onnodig zorgwekkende berichten te sturen. Het is cruciaal om je wachttijden zorgvuldig in te stellen om een veiligheidsbuffer in te bouwen. Geef jezelf voldoende tijd om je status te bevestigen, zelfs als je je telefoon thuis bent vergeten of anderszins vertraagd bent.",
        layeredApproach: "Overweeg een gelaagde aanpak voor je noodplan. Bijvoorbeeld:",
        firstDelay: "Eerste wachttijd (bv. 4 uur na check-in):",
        firstDelayText: "Breng een buur op de hoogte voor een snelle controle.",
        secondDelay: "Tweede wachttijd (bv. 6 uur):",
        secondDelayText: "Waarschuw een familielid dat verder weg woont.",
        thirdDelay: "Derde wachttijd (bv. 8 uur):",
        thirdDelayText: "Neem contact op met de hulpdiensten als laatste stap.",
        missedCheckin: "Wat gebeurt er als je een inchecken mist?",
        missedCheckinText: "Als je een check-in mist, wordt het waarschuwingssysteem van de app geactiveerd. De app begint elk half uur een hoorbare herinnering af te spelen en blijft dit doen totdat je bevestigt dat je in orde bent.",
        crucially: "Cruciaal is dat er geen alerts worden verzonden als je je status bevestigt voordat de wachttijd van je eerste alert is verstreken. Het systeem is ontworpen om je voldoende tijd te geven om te reageren en valse alarmen te voorkomen.",
        confirmText: "Als je niet binnen de geconfigureerde tijd bevestigt, zal de app doorgaan met het uitvoeren van je vooraf gedefinieerde alerts. Je contacten ontvangen dan de berichten die je hebt voorbereid, inclusief je noodplan.",
        dataStorage: "Gegevensopslag",
        dataStorageText: "Alle gegevens die je in de I'm OK app invoert, worden uitsluitend lokaal op je apparaat opgeslagen. De app vereist geen internetverbinding voor de kernfunctionaliteiten en stuurt je persoonlijke gegevens nergens naartoe. De opgeslagen gegevens zijn:",
        settings: "Instellingen:",
        settingsText: "Je naam, de inchecktijd, je noodplan en de geconfigureerde acties (SMS/e-mail) worden lokaal opgeslagen.",
        statusInfo: "Statusinformatie:",
        statusInfoText: "De app volgt lokaal bij wanneer het laatste succesvolle inchecken was en of er meldingen zijn gemist.",
        requiredPermissions: "Vereiste toestemmingen",
        requiredPermissionsText: "Om correct te functioneren vereist de I'm OK-app de volgende toestemmingen:",
        notifications: "Meldingen (POST_NOTIFICATIONS):",
        notificationsText: "Nodig om je dagelijks inchecken herinneringen te sturen.",
        alarms: "Alarmen en herinneringen (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Gebruikt om ervoor te zorgen dat de incheckmededeling op het exacte ingestelde moment wordt bezorgd, zelfs als het apparaat inactief is.",
        sms: "SMS-berichten verzenden (SEND_SMS):",
        smsText: "Stelt de app in staat om een SMS namens jou naar je contacten te sturen als je een inchecken mist.",
        readContacts: "Contacten lezen (READ_CONTACTS):",
        readContactsText: "Stelt je in staat om een ontvanger voor een actie rechtstreeks uit je contactlijst te selecteren. De app leest alleen de geselecteerde contactgegevens en slaat deze niet voor andere doeleinden op.",
        foreground: "Voorgrondservice (FOREGROUND_SERVICE):",
        foregroundText: "Zorgt ervoor dat de app acties op betrouwbare wijze kan uitvoeren (zoals het verzenden van een SMS of e-mail), zelfs wanneer de app op de achtergrond wordt uitgevoerd.",
        inAppPurchases: "In-app aankopen (BILLING):",
        inAppPurchasesText: "Stelt je in staat donaties te doen ter ondersteuning van de app-ontwikkeling.",
        preventPhone: "Telefoon voorkomen van slapen (WAKE_LOCK):",
        preventPhoneText: "Zorgt ervoor dat de app acties op betrouwbare wijze kan uitvoeren (zoals het verzenden van een SMS of e-mail), zelfs wanneer het apparaat in de slaapstand staat.",
        runOnStartup: "Bij opstarten uitvoeren (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Stelt de app in staat automatisch te starten wanneer je apparaat wordt ingeschakeld.",
        contactRequests: "Contact & Verzoeken:",
        developedBy: "Ontwikkeld door:",
        aspiesApps: "Aspie's Apps",
        feedback: "Vragen of feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Met zorg voor mensen en hun huisdieren.",
        whyThisApp: "Waarom deze app?",
        howToUse: "Hoe te gebruiken?",
        privacyPermissions: "Privacy & Permissies:",
        withCare: "Met zorg voor mens en dier.",
    },
    fr: {
        why: "Pourquoi cette app?",
        how: "Comment l'utiliser?",
        privacy: "Confidentialité & Autorisations.",
        contact: "Contact & Demandes.",
        donate: "Donner",
        tagline: "Un filet de sécurité autonome pour vous et vos animaux de compagnie.",
        downloadBtn: "Télécharger sur Google Play",
        coreIdea: "L'idée de base : l'indépendance, assurée",
        para1: "Vivre seul s'accompagne d'une inquiétude silencieuse et persistante: \"Et s'il m'arrivait quelque chose? Combien de temps s'écoulerait-il avant que quelqu'un le sache?\" Pour ceux qui chérissent leur indépendance mais reconnaissent la réalité de la vie en solo, cette question mérite une réponse simple, fiable et privée.",
        para2: "I'm OK est votre filet de sécurité personnel et automatisé. C'est un outil honnête pour la tranquillité d'esprit. Ce n'est pas un tracker; il respecte votre vie privée tout en veillant discrètement sur votre bien-être. Il est conçu pour l'esprit indépendant qui veut soulager ses proches de leurs soucis, sans sacrifier leur autonomie.",
        para3: "Selon un horaire que vous définissez, l'application vous envoie une notification discrète. Un simple clic sur le bouton \"I'm OK\" suffit pour confirmer votre bien-être. Si cette confirmation n'a pas lieu, et seulement alors, vos alertes d'urgence personnelles et prédéfinies sont déclenchées.",
        personalStory: "Une histoire personnelle: la raison d'être",
        para4: "\"J'ai développé cette application à partir d'un besoin personnel. En tant que personne vivant seule avec des contacts sociaux limités, ma plus grande préoccupation n'était pas pour moi-même, mais pour mon petit chien, Mara. C'est elle qui me pousse à sortir, la raison d'être de cette application: m'assurer qu'elle ne soit jamais laissée seule.",
        para5: "Je suis l'une de ces personnes que l'on retrouve parfois dans les journaux, retrouvée chez elle des mois plus tard. Que je sois retrouvé dans cet état n'est pas mon problème à ce moment. Mais m'assurer que mon petit chien soit secouru, si. Cette application est la réponse à cette question. C'est ma façon de lui rendre la pareille. Elle me maintient en vie, et je construis un système qui garantit sa sécurité.",
        para6: "C'est un outil conçu pour offrir un filet de sécurité, pas seulement pour moi, mais pour toute personne dans une situation similaire. C'est un moyen de s'assurer qu'en cas d'urgence, de l'aide est en route pour ceux qui dépendent de nous, qu'ils aient deux ou quatre pattes.\"",
	bothMara: "\"Mara et moi pourrions vraiment utiliser un peu de soutien. Si vous êtes satisfait de cette application gratuite, envisagez de nous offrir un café ou un os...\"",
        howItWorks: "Comment ça marche: Le système patient à trois étages",
        philosophy: "La philosophie de I'm OK est la fiabilité et l'évitement des fausses alarmes. Ce n'est pas conçue pour la vitesse, mais pour la certitude.",
        dailyCheckin: "Le Check-in.",
        dailyCheckinText: "Conformément à un horaire que vous avez défini, vous recevez une seule notification. Un simple appui sur \"Je vais bien\" suffit. L'application disparaît alors en arrière-plan.",
        audibleReminder: "Le rappel sonore.",
        audibleReminderText: "Vous avez manqué la première notification? Ne vous inquiétez pas. L'application sait que les gens oublient leur téléphone. Au bout d'un certain temps, elle émettra un rappel sonore toutes les demi-heures. C'est un tampon intégré qui vous donne des heures pour réagir à un simple oubli.",
        emergencyPlan: "Les alertes d'urgence en action.",
        emergencyPlanText: "Ce n'est qu'après une longue période d'absence de réponse, une durée que vous contrôlez, que le plan d'urgence s'active.",
        familyFriends: "Pour la famille et les amis: Tranquillité d'esprit partagée",
        para7: "Êtes-vous un fils, une fille ou un petit-enfant inquiet pour un parent ou grand-parent qui vit seul? \"I'm OK\" offre un moyen non intrusif de s'assurer qu'ils sont en sécurité. Il vous offre un sentiment de sécurité sans perturber leur précieuse indépendance. En les aidant à configurer l'application, vous saurez qu'un système fiable est en place, veillant sur eux lorsque vous ne le pouvez pas.",
        howDoesWork: "Comment fonctionne l'application I'm OK?",
        howDoesWorkText: "L'application I'm OK est conçue pour assurer votre sécurité en vous contactant selon un horaire flexible que vous définissez. Si vous ne confirmez pas à temps, l'application peut informer automatiquement vos contacts.",
        settingUpCheckin: "Configuration de votre filet de sécurité",
        setupText: "Allez dans les pages principales \"Check-in\" et \"Info & Plan\" pour configurer l'application. Ici, vous pouvez définir les éléments suivants:",
        checkinTime: "Calendrier de check-in:",
        checkinTimeText: "Sur la page \"Check-in\", vous pouvez choisir la fréquence à laquelle vous souhaitez recevoir une notification. Définissez l'intervalle, la plage horaire (par exemple, de 9h à 22h) et les jours de la semaine où le calendrier est actif.",
        yourName: "Votre nom:",
        yourNameText: "Sur la page \"Info & Plan\", entrez votre nom. Ce nom est utilisé dans les messages envoyés à vos contacts.",
        emergencyPlanSetup: "Plan d'urgence:",
        emergencyPlanSetupText: "Également sur la page \"Info & Plan\", créez un plan d'urgence. Ce plan est inclus dans les messages envoyés à vos contacts.",
        settingUpActions: "Configuration des alertes",
        actionsText: "Sur la page \"Alertes\", vous pouvez définir qui doit recevoir un message si vous ne répondez pas au check-in. Vous pouvez choisir entre SMS et e-mail. Réglez le délai (en heures et minutes) après lequel le message doit être envoyé. Vous pouvez ajouter plusieurs alertes.",
        smartApproach: "Une approche intelligente pour définir les délais",
        smartApproachText: "Le but de cette application est d'alerter quelqu'un en cas de véritable urgence, pas d'envoyer des messages inquiétants inutilement. Il est crucial de définir vos délais de manière réfléchie pour créer une marge de sécurité. Donnez-vous suffisamment de temps pour confirmer votre statut, même si vous avez oublié votre téléphone à la maison ou si vous êtes en retard.",
        layeredApproach: "Envisagez une approche à plusieurs niveaux pour votre plan d'urgence. Par exemple:",
        firstDelay: "Premier délai (par exemple, 4 heures après le check-in):",
        firstDelayText: "Avertir un voisin proche pour une vérification rapide.",
        secondDelay: "Deuxième délai (par exemple, 6 heures):",
        secondDelayText: "Alerter un membre de la famille qui vit plus loin.",
        thirdDelay: "Troisième délai (par exemple, 8 heures):",
        thirdDelayText: "Contacter les services d'urgence en dernier recours.",
        missedCheckin: "Que se passe-t-il si vous manquez un check-in?",
        missedCheckinText: "Si vous manquez un check-in, le système d'alerte de l'application est activé. L'application commencera à émettre un rappel sonore toutes les demi-heures et continuera jusqu'à ce que vous confirmiez que vous allez bien.",
        crucially: "Il est crucial de noter qu'aucune alerte ne sera envoyée si vous confirmez votre statut avant que le délai de votre première alerte ne soit écoulé. Le système est conçu pour vous donner amplement de temps pour répondre et d'éviter les fausses alarmes.",
        confirmText: "Si vous ne confirmez pas dans le délai configuré, l'application procédera à l'exécution de vos alertes prédéfinies. Vos contacts recevront alors les messages que vous avez préparés, y compris votre plan d'urgence.",
        dataStorage: "Stockage des données",
        dataStorageText: "Toutes les données que vous saisissez dans l'application I'm OK sont stockées exclusivement localement sur votre appareil. L'application ne nécessite pas de connexion Internet pour ses fonctionnalités de base et n'envoie vos données personnelles nulle part. Les données stockées comprennent:",
        settings: "Paramètres:",
        settingsText: "Votre nom, l'heure de check-in, votre plan d'urgence et les alertes configurées (SMS/e-mail) sont stockés localement.",
        statusInfo: "Informations sur de statut:",
        statusInfoText: "L'application suit localement la date du dernier check-in réussi et si des notifications ont été manquées.",
        requiredPermissions: "Autorisations requises",
        requiredPermissionsText: "Pour fonctionner correctement, l'application I'm OK nécessite les autorisations suivantes :",
        notifications: "Notifications (POST_NOTIFICATIONS):",
        notificationsText: "Nécessaire pour vous envoyer le rappel d'enregistrement quotidien.",
        alarms: "Alarmes et rappels (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Utilisé pour garantir que la notification de check-in est livrée à l'heure exacte définie, même si l'appareil est inactif.",
        sms: "Envoyer des messages SMS (SEND_SMS):",
        smsText: "Permet à l'application d'envoyer un SMS en votre nom à vos contacts si vous manquez un check-in.",
        readContacts: "Lire les contacts (READ_CONTACTS):",
        readContactsText: "Vous permet de sélectionner un destinataire pour une alerte directement à partir de votre liste de contacts. L'application ne lit que les informations de contact sélectionnées et ne les stocke pas à d'autres fins.",
        foreground: "Service de premier plan (FOREGROUND_SERVICE):",
        foregroundText: "Garantit que l'application peut exécuter de manière fiable des alertes (telles que l'envoi d'un SMS ou d'un e-mail), même lorsque l'application s'exécute en arrière-plan.",
        inAppPurchases: "Achats intégrés (BILLING):",
        inAppPurchasesText: "Vous permet de faire des dons pour soutenir le développement de l'application.",
        preventPhone: "Empêcher le téléphone de se mettre en veille (WAKE_LOCK):",
        preventPhoneText: "S'assure que l'application peut effectuer des alertes (comme l'envoi d'un SMS ou d'un e-mail) sans être interrompue par la mise en veille de l'appareil.",
        runOnStartup: "Exécuter au démarrage (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Permet à l'application de replanifier automatiquement votre check-in quotidien après le redémarrage de votre appareil.",
        internet: "Internet (INTERNET):",
        internetText: "Requis pour l'envoi d'alertes par e-mail et pour faire des dons volontaires via l'application.",

        contactRequests: "Contact & Demandes:",
        developedBy: "Développé par:",
        aspiesApps: "Aspie's Apps",
        feedback: "Questions ou commentaires?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Avec soin pour les gens et leurs animaux de compagnie.",
        whyThisApp: "Pourquoi cette application?",
        howToUse: "Comment utiliser?",
        privacyPermissions: "Confidentialité et permissions:",
        withCare: "Avec soin pour les gens et leurs animaux de compagnie.",
    },
    de: {
        why: "Warum diese App?",
        how: "Wie man es benutzt?",
        privacy: "Datenschutz & Genehmigungen.",
        contact: "Kontakt & Anfragen.",
        donate: "Spenden",
        tagline: "Ein autonomes Sicherheitsnetz für Sie und Ihre Haustiere.",
        downloadBtn: "Im Google Play Store erhältlich",
        coreIdea: "Die Kernidee: Unabhängigkeit, gesichert",
        para1: "Allein zu leben bringt eine leise, anhaltende Sorge mit sich: \"Was wäre, wenn mir etwas zustoßen würde? Wie lange würde es dauern, bis jemand davon erfährt?\" Für diejenigen, die ihre Unabhängigkeit schätzen, aber die Realität des Alleinlebens anerkennen, verdient diese Frage eine einfache, zuverlässige und private Antwort.",
        para2: "I'm OK ist Ihr persönliches, automatisiertes Sicherheitsnetz. Es ist ein ehrliches Werkzeug für den Seelenfrieden. Es ist kein Tracker; es respektiert Ihre Privatsphäre, während es diskret über Ihr Wohlbefinden wacht. Es ist für den unabhängigen Geist konzipiert, der seine Lieben von Sorgen befreien möchte, ohne seine Autonomie zu opfern.",
        para3: "Nach einem von Ihnen festgelegten Zeitplan sendet Ihnen die App eine einzige diskrete Benachrichtigung. Ein einfacher Fingertipp der Schaltfläche \"I'm OK\" genügt, um Ihr Wohlbefinden zu bestätigen. Wenn diese Bestätigung ausbleibt, und nur dann, werden Ihre persönlichen, vordefinierter Notfallalarme ausgelöst.",
        personalStory: "Eine persönliche Geschichte: Der Grund, warum",
        para4: "\"Ich habe diese App aus einem persönlichen Bedürfnis heraus entwickelt. Als jemand, der allein lebt und nur begrenzte soziale Kontakte hat, war meine größte Sorge nicht ich selbst, sondern mein kleiner Hund Mara. Sie ist der Grund, warum ich nach draußen gehe, der Grund, warum diese App existiert: um sicherzustellen, dass sie niemals allein gelassen wird.",
        para5: "Ich bin einer dieser Menschen, von denen man manchmal in der Zeitung liest, die Monate später in ihrem Haus gefunden werden. Ob ich in diesem Zustand gefunden werde, ist in diesem Moment nicht mein Problem. Aber sicherzustellen, dass mein Hund gerettet wird, ist es. Diese App ist die Antwort auf diese Frage. Es ist meine Art, ihr etwas zurückzugeben. Sie hält mich am Leben, und ich baue ein System auf, das ihre Sicherheit garantiert.",
        para6: "Es ist ein Werkzeug, das geschaffen wurde, um ein Sicherheitsnetz zu bieten, nicht nur für mich, sondern für jeden in einer ähnlichen Situation. Es ist eine Möglichkeit, sicherzustellen, dass im Notfall Hilfe für diejenigen unterwegs ist, die von uns abhängig sind, egal ob sie zwei oder vier Beine haben.\"",
	bothMara: "\"Sowohl Mara als auch ich könnten wirklich etwas Unterstützung gebrauchen. Wenn Sie mit dieser kostenlosen App zufrieden sind, denken Sie darüber nach, einen Kaffee oder einen Knochen anzubieten...\"",
        howItWorks: "Wie es funktioniert: Das geduldige dreistufige System",
        philosophy: "Die Philosophie von I'm OK ist Zuverlässigkeit und die Vermeidung von Fehlalarmen. Es ist nicht auf Geschwindigkeit ausgelegt, sondern auf Sicherheit.",
        dailyCheckin: "Der Check-in.",
        dailyCheckinText: "Gemäß einem von Ihnen festgelegten Zeitplan erhalten Sie eine Benachrichtigung. Ein Fingertipp auf \"I'm OK\" genügt. Die App verschwindet dann wieder im Hintergrund.",
        audibleReminder: "Die akustische Erinnerung.",
        audibleReminderText: "Haben Sie die erste Benachrichtigung verpasst? Keine Sorge. Die App weiß, dass die Leute ihre Telefone vergessen. Nach einer Weile ertönt jede halbe Stunde eine akustische Erinnerung. Dies ist ein eingebauter Puffer, der Ihnen Stunden Zeit gibt, auf ein einfaches Versehen zu reagieren.",
        emergencyPlan: "Der Notfallplan in Aktion.",
        emergencyPlanText: "Erst nach einer langen Zeit der Nichtreaktion, eine Dauer, die Sie steuern, wird das Notfallalarmsystem aktiviert.",
        familyFriends: "Für Familie und Freunde: Geteilter Seelenfrieden",
        para7: "Sind Sie ein Sohn, eine Tochter oder ein Enkelkind, das sich um einen allein lebenden Elternteil oder Großelternteil sorgt? \"I'm OK\" bietet eine unaufdringliche Möglichkeit, um sicherzustellen, dass sie in Sicherheit sind. Es bietet Ihnen ein Gefühl der Sicherheit, ohne ihre geschätzte Unabhängigkeit zu stören. Indem Sie ihnen helfen, die App einzurichten, wissen Sie, dass ein zuverlässiges System vorhanden ist, das über sie wacht, wenn Sie es nicht können.",
        howDoesWork: "Wie funktioniert die I'm OK App?",
        howDoesWorkText: "Die I'm OK App wurde entwickelt, um Ihre Sicherheit zu gewährleisten, indem sie sich nach einem von Ihnen festgelegten flexiblen Zeitplan bei Ihnen meldet. Wenn Sie nicht rechtzeitig bestätigen, kann die App Ihre Kontakte automatisch informieren.",
        settingUpCheckin: "Einrichten Ihres Sicherheitsnetzes",
        setupText: "Gehen Sie zu den Seiten \"Check-in\" und \"Info & Plan\" um die App zu konfigurieren. Hier können Sie Folgendes einstellen:",
        checkinTime: "Check-in Zeitplan:",
        checkinTimeText: "Auf der Seite \"Check-in\" können Sie festlegen, wie oft Sie eine Benachrichtigung erhalten möchten. Stellen Sie das Intervall, den Zeitbereich (z.B. von 9 bis 22 Uhr) und die Wochentage ein, an denen der Zeitplan aktiv ist.",
        yourName: "Ihr Name:",
        yourNameText: "Geben Sie auf der Seite \"Info & Plan\" Ihren Namen ein. Dieser Name wird in den Nachrichten verwendet, die an Ihre Kontakte gesendet werden.",
        emergencyPlanSetup: "Notfallplan:",
        emergencyPlanSetupText: "Erstellen Sie auf der seite \"Info & Plan\" einen Notfallplan. Dieser Plan wird in die Nachrichten aufgenommen, die an Ihre Kontakte gesendet werden.",
        settingUpActions: "Alarme Einrichten",
        actionsText: "Auf der Seite \"Alarme\" können Sie festlegen, wer eine Nachricht erhalten soll, wenn Sie nicht auf den Check-in reagieren. Sie können zwischen SMS und E-Mail wählen. Legen Sie die Verzögerung (in Stunden und Minuten) fest, nach der die Nachricht gesendet werden soll. Sie können mehrere Aktionen hinzufügen.",
        smartApproach: "Ein intelligenter Ansatz zum Einstellen von Verzögerungen",
        smartApproachText: "Der Zweck dieser App ist es, jemanden in einem echten Notfall zu alarmieren, nicht unnötig beunruhigende Nachrichten zu senden. Es ist entscheidend, das Sie Ihre Verzögerungen sorgfältig einzustellen, um einen Sicherheitspuffer einzubauen. Geben Sie sich genügend Zeit, um Ihren Status zu bestätigen, auch wenn Sie Ihr Telefon zu Hause vergessen haben oder anderweitig verspätet sind.",
        layeredApproach: "Erwägen Sie einen mehrstufigen Ansatz für Ihren Notfallplan. Zum Beispiel:",
        firstDelay: "Erste Verzögerung (z. B. 4 Stunden nach dem Check-in):",
        firstDelayText: "Benachrichtigen Sie einen nahen Nachbarn für eine schnelle Überprüfung.",
        secondDelay: "Zweite Verzögerung (z. B. 6 Stunden):",
        secondDelayText: "Benachrichtigen Sie ein Familienmitglied, das weiter weg wohnt.",
        thirdDelay: "Dritte Verzögerung (z. B. 8 Stunden):",
        thirdDelayText: "Kontaktieren Sie den Notdienst als letzten Schritt.",
        missedCheckin: "Was passiert, wenn Sie einen Check-in verpassen?",
        missedCheckinText: "Wenn Sie einen Check-in verpassen, wird das Alarmsystem der App aktiviert. Die App beginnt, jede halbe Stunde eine akustische Erinnerung abzuspielen, und wird dies so lange tun, bis Sie bestätigen, dass es Ihnen gut geht.",
        crucially: "Entscheidend ist, dass keine Alarme gesendet werden, wenn Sie Ihren Status bestätigen, bevor die Verzögerung Ihrer ersten Alarms abgelaufen ist. Das System ist so konzipiert, dass Sie genügend Zeit haben, zu reagieren und Fehlalarme zu vermeiden.",
        confirmText: "Wenn Sie nicht innerhalb der konfigurierten Zeit bestätigen, führt die App Ihre vordefinierten Alarme aus. Ihre Kontakte erhalten dann die von Ihnen vorbereiteten Nachrichten, einschließlich Ihres Notfallplans.",
        dataStorage: "Datenspeicherung",
        dataStorageText: "Alle Daten, die Sie in der I'm OK App eingeben, werden ausschließlich lokal auf Ihrem Gerät gespeichert. Die App erfordert keine Internetverbindung für ihre Kernfunktionalität und sendet Ihre persönlichen Daten nirgendwo hin. Die gespeicherten Daten umfassen:",
        settings: "Einstellungen:",
        settingsText: "Ihr Name, die Check-in-Zeit, Ihr Notfallplan und die konfigurierten Alarme (SMS/E-Mail) werden lokal gespeichert.",
        statusInfo: "Statusinformationen:",
        statusInfoText: "Die App verfolgt lokal, wann der letzte erfolgreiche Check-in stattgefunden hat und ob Benachrichtigungen verpasst wurden.",
        requiredPermissions: "Erforderliche Genehmigungen",
        requiredPermissionsText: "Um ordnungsgemäß zu funktionieren, benötigt die I'm OK-App die folgenden Berechtigungen:",
        notifications: "Benachrichtigungen (POST_NOTIFICATIONS):",
        notificationsText: "Erforderlich, um Ihnen die tägliche Check-in-Erinnerung zu senden.",
        alarms: "Alarme und Erinnerungen (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Wird verwendet, um sicherzustellen, dass die Check-in-Benachrichtigung zur genau eingestellten Zeit zugestellt wird, auch wenn das Gerät inaktiv ist.",
        inAppPurchases: "In-App-Käufe (BILLING):",
        inAppPurchasesText: "Ermöglicht es Ihnen, Spenden zur Unterstützung der App-Entwicklung zu tätigen.",
        preventPhone: "Verhindern, dass das Telefon in den Ruhezustand wechselt (WAKE_LOCK):",
        preventPhoneText: "Stellt sicher, dass die App Alarme ausführen kann (wie das Senden einer SMS oder E-Mail), ohne durch den Ruhezustand des Geräts unterbrochen zu werden.",
        runOnStartup: "Beim Start ausführen (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Ermöglicht der App, Ihren täglichen Check-in nach einem Neustart Ihres Geräts automatisch neu zu plannen.",
        sms: "SMS-Nachrichten senden (SEND_SMS):",
        smsText: "Ermöglicht der App, im Notfall eine SMS im Namen Ihrer Kontakte zu senden, wenn Sie einen Check-in verpassen.",
        readContacts: "Kontakte lesen (READ_CONTACTS):",
        readContactsText: "Ermöglicht es Ihnen, einen Empfänger für eine Alarm direkt aus Ihrer Kontaktliste auszuwählen. Die App liest nur die ausgewählten Kontaktinformationen und speichert sie nicht für andere Zwecke.",
        foreground: "Vordergrunddienst (FOREGROUND_SERVICE):",
        foregroundText: "Stellt sicher, dass die App zuverlässig Alarme ausführen kann (z. B. das Senden einer SMS oder E-Mail), auch wenn die App im Hintergrund ausgeführt wird.",
        internet: "Internet (INTERNET):",
        internetText: "Erforderlich für das Senden von E-Mail_Warnungen und für freiwillige Spenden über die App.",

        contactRequests: "Kontakt & Anfragen:",
        developedBy: "Entwickelt von:",
        aspiesApps: "Aspie's Apps",
        feedback: "Fragen oder Feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Mit Sorgfalt für Menschen und ihre Haustiere.",
        whyThisApp: "Warum diese App?",
        howToUse: "Wie man es benutzt?",
        privacyPermissions: "Datenschutz & Berechtigungen:",
        withCare: "Mit Sorgfalt für Menschen und ihre Haustiere.",
    }
};

function changeLanguage(lang) {
    localStorage.setItem('language', lang);
    updatePageLanguage(lang);
}

function updatePageLanguage(lang) {
    const trans = translations[lang] || translations.en;
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (trans[key]) {
            if (element.id === 'footer-text') {
                element.innerHTML = trans[key];
            } else {
                element.textContent = trans[key];
            }
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('language') || 'en';
    document.getElementById('language-select').value = savedLang;
    updatePageLanguage(savedLang);
});