const translations = {
    en: {
        why: "Why this app?",
        how: "How to use?",
        privacy: "Privacy & Permissions.",
        contact: "Contact & Requests.",
        donate: "Donate",
        tagline: "An autonomous safety net for you and your pets.",
        downloadBtn: "Get it on Google Play",
        coreIdea: "The Core Idea: Independence, Secured",
        para1: "Living alone comes with a quiet, persistent worry: \"What if something happened to me? How long would it be before someone knew?\" For those who cherish their independence but acknowledge the reality of living solo, this question deserves a simple, reliable, and private answer.",
        para2: "I'm OK is your personal, automated safety net. It is an honest tool for peace of mind. It is not a tracker; it respects your privacy while discreetly watching over your well-being. It is designed for the independent spirit who wants to relieve their loved ones of worry, without sacrificing their autonomy.",
        para3: "Every day, at a time you choose, the app sends you a single, discreet notification. A simple tap on the \"I'm OK\" button is all it takes to confirm your well-being. If that confirmation doesn't happen, and only then, your personal, pre-defined emergency plan is set in motion.",
        personalStory: "A Personal Story: The Reason Why",
        para4: "\"I developed this app from a personal need. As someone who lives alone and has limited social contact, my biggest concern wasn't for myself, but for my little dog, Mara. She is the reason I go outside, the reason this app exists: to ensure she would never be left alone.",
        para5: "I am one of those people you sometimes read about in the newspaper, found in their home months later. Whether I'm found in that state isn't my problem at that moment. But ensuring my dog is rescued, is. This app is the answer to that question. It is my way of giving back to her. She keeps me alive, and I am building a system that guarantees her safety.",
        para6: "It's a tool built to provide a safety net, not just for me, but for anyone in a similar situation. It's a way to ensure that in an emergency, help is on the way for those who depend on us, whether they have two legs or four.\"",
        howItWorks: "How It Works: The Patient, Three-Stage System",
        philosophy: "The philosophy of I'm OK is reliability and the avoidance of false alarms. It is not built for speed, but for certainty.",
        dailyCheckin: "The Daily Check-in.",
        dailyCheckinText: "You choose a fixed moment in your day, perhaps with your morning coffee. You receive a single notification. One tap on \"I'm OK\" is enough. The app then disappears back into the background.",
        audibleReminder: "The Audible Reminder.",
        audibleReminderText: "Did you miss the first notification? Don't worry. The app knows that people forget their phones. After the first hour, it will only produce a discreet sound signal at intervals. No extra visual notifications to cause alarm. This is a built-in buffer, giving you hours to respond to a simple oversight.",
        emergencyPlan: "The Emergency Plan in Action.",
        emergencyPlanText: "Only after a long period of unresponsiveness, a duration you control, does the emergency plan activate.",
        familyFriends: "For Family and Friends: Shared Peace of Mind",
        para7: "Are you a son, daughter, or grandchild worried about a parent or grandparent who lives alone? \"I'm OK\" provides a non-intrusive way to ensure they are safe. It offers you a feeling of security without disturbing their cherished independence. By helping them set up the app, you will know that a reliable system is in place, watching over them when you can't.",
        howDoesWork: "How does the I'm OK app work?",
        howDoesWorkText: "The I'm OK app is designed to ensure your safety by checking in with you daily at a set time. If you do not confirm in time, the app can automatically inform your contacts.",
        settingUpCheckin: "Setting up the daily check-in",
        setupText: "Go to \"Emergency Plan\" to configure the app. Here you can set the following:",
        checkinTime: "Check-in time:",
        checkinTimeText: "Choose the time you want to receive a daily notification to confirm you are okay.",
        yourName: "Your name:",
        yourNameText: "Enter your name. This name is used in the messages sent to your contacts.",
        emergencyPlanSetup: "Emergency Plan:",
        emergencyPlanSetupText: "Create an emergency plan that will be included in the messages. Here you can provide instructions such as \"first call my mobile, then come by, and then call emergency services\".",
        settingUpActions: "Setting up Actions",
        actionsText: "In the \"Actions\" section of the settings, you can define who should receive a message if you do not respond to the check-in. You can choose between SMS and email. Set the delay (in hours and minutes) after which the message should be sent. You can add multiple actions.",
        smartApproach: "A Smart Approach to Setting Delays",
        smartApproachText: "The purpose of this app is to alert someone in a true emergency, not to send worrying messages unnecessarily. It is crucial to set your delays thoughtfully to build in a safety buffer. Give yourself enough time to confirm your status, even if you've forgotten your phone at home or are otherwise delayed.",
        layeredApproach: "Consider a layered approach to your emergency plan. For example:",
        firstDelay: "First delay (e.g., 12 hours after check-in):",
        firstDelayText: "Notify a close neighbor for a quick wellness check.",
        secondDelay: "Second delay (e.g., 18 hours):",
        secondDelayText: "Alert a family member who lives further away.",
        thirdDelay: "Third delay (e.g., 24 hours):",
        thirdDelayText: "Contact emergency services as a final step.",
        missedCheckin: "What happens if you miss a check-in?",
        missedCheckinText: "If you miss your daily check-in, the app's alert system is activated. The app will begin to play an audible reminder every hour and will continue to do so until you confirm that you are okay.",
        crucially: "Crucially, no actions will be sent if you confirm your status before the delay of your first action has passed. The system is designed to give you ample time to respond and avoid false alarms.",
        confirmText: "If you do not confirm within the configured time, the app will proceed to execute your predefined actions. Your contacts will then receive the messages you have prepared, including your emergency plan.",
        dataStorage: "Data Storage",
        dataStorageText: "All data you enter in the I'm OK app is stored exclusively locally on your device. The app does not require an internet connection for its core functionalities and does not send your personal data anywhere. The stored data includes:",
        settings: "Settings:",
        settingsText: "Your name, the check-in time, your emergency plan, and the configured actions (SMS/email) are stored locally.",
        statusInfo: "Status Information:",
        statusInfoText: "The app locally tracks when the last successful check-in was and if any notifications have been missed.",
        requiredPermissions: "Required Permissions",
        requiredPermissionsText: "To function correctly, the I'm OK app requires the following permissions:",
        notifications: "Notifications (POST_NOTIFICATIONS):",
        notificationsText: "Necessary to send you the daily check-in reminder.",
        alarms: "Alarms and Reminders (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Used to ensure the check-in notification is delivered at the exact set time, even if the device is inactive.",
        sms: "Send SMS messages (SEND_SMS):",
        smsText: "Allows the app to send an SMS on your behalf to your contacts if you miss a check-in.",
        readContacts: "Read contacts (READ_CONTACTS):",
        readContactsText: "Allows you to select a recipient for an action directly from your contact list. The app only reads the selected contact information and does not store it for other purposes.",
        foreground: "Foreground service (FOREGROUND_SERVICE):",
        foregroundText: "Ensures that the app can reliably perform actions (such as sending an SMS or email), even when the app is running in the background.",
        inAppPurchases: "In-app purchases (BILLING):",
        inAppPurchasesText: "Allows you to make donations to support the app's development.",
        preventPhone: "Prevent phone from sleeping (WAKE_LOCK):",
        preventPhoneText: "Ensures that the app can reliably perform actions (such as sending an SMS or email), even when the device is in sleep mode.",
        runOnStartup: "Run on startup (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Enables the app to automatically start when your device is turned on.",
        contactRequests: "Contact & Requests:",
        developedBy: "Developed by:",
        aspiesApps: "Aspie's Apps",
        feedback: "Questions or feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | With care for people and their pets.",
        whyThisApp: "Why this app?",
        howToUse: "How to use?",
        privacyPermissions: "Privacy & Permissions:",
        withCare: "With care for people and their pets.",
    },
    nl: {
        why: "Waarom deze app?",
        how: "Hoe te gebruiken?",
        privacy: "Privacy & Toestemmingen.",
        contact: "Contact & Verzoeken.",
        donate: "Doneer",
        tagline: "Een autonoom veiligheidssysteem voor jou en je huisdieren.",
        downloadBtn: "Krijg het op Google Play",
        coreIdea: "Het kernidee: Onafhankelijkheid, beveiligd",
        para1: "Alleen wonen brengt een stil, voortdurend bezorgdheid mee: \"Wat gebeurt er als mij iets overkomt? Hoe lang duurt het voordat iemand het weet?\" Voor degenen die hun onafhankelijkheid koesteren, maar het realiteit van alleen wonen erkennen, verdient deze vraag een eenvoudig, betrouwbaar en privé antwoord.",
        para2: "I'm OK is je persoonlijke, geautomatiseerde veiligheidssysteem. Het is een eerlijk hulpmiddel voor gemoedsrust. Het is geen tracker; het respecteert je privacy terwijl het discreet toeziet op je welzijn. Het is ontworpen voor de onafhankelijke geest die zijn dierbaren van zorgen wil verlichten, zonder hun autonomie op te geven.",
        para3: "Elke dag, op een moment dat je kiest, stuurt de app je één discrete melding. Een simpele tikje op de \"I'm OK\" knop is alles wat nodig is om je welzijn te bevestigen. Als die bevestiging niet gebeurt, en alleen dan, wordt je persoonlijke, vooraf bepaalde noodplan in werking gesteld.",
        personalStory: "Een persoonlijk verhaal: Waarom",
        para4: "\"Ik heb deze app uit persoonlijke behoefte ontwikkeld. Als iemand die alleen woont en beperkt sociaal contact heeft, was mijn grootste zorg niet voor mijzelf, maar voor mijn kleine hond, Mara. Ze is de reden dat ik naar buiten ga, de reden dat deze app bestaat: om ervoor te zorgen dat ze nooit alleen zou worden achtergelaten.",
        para5: "Ik ben een van die mensen over wie je soms in de krant leest, maanden later in hun huis gevonden. Of ik in die toestand word gevonden, is op dat moment mijn probleem niet. Maar ervoor zorgen dat mijn hond wordt gered, is dat wel. Deze app is het antwoord op die vraag. Het is mijn manier om het haar terugbetaald zetten. Ze houdt me in leven, en ik bouw een systeem dat haar veiligheid garandeert.",
        para6: "Het is een hulpmiddel dat is gebouwd om een veiligheidsnet te bieden, niet alleen voor mij, maar voor iedereen in een soortgelijke situatie. Het is een manier om ervoor te zorgen dat in geval van nood hulp onderweg is naar degenen die van ons afhangen, of ze nu twee benen of vier hebben.\"",
        howItWorks: "Hoe het werkt: Het geduldigde drielagensysteem",
        philosophy: "De filosofie van I'm OK is betrouwbaarheid en het vermijden van valse alarmen. Het is niet gebouwd voor snelheid, maar voor zekerheid.",
        dailyCheckin: "Het dagelijkse inchecken.",
        dailyCheckinText: "Je kiest een vast moment in je dag, misschien met je ochtendkoffie. Je ontvangt één melding. Een tikje op \"I'm OK\" is genoeg. De app verdwijnt dan terug op de achtergrond.",
        audibleReminder: "De hoorbare herinnering.",
        audibleReminderText: "Heb je de eerste melding gemist? Maak je geen zorgen. De app weet dat mensen hun telefoons vergeten. Na het eerste uur zal het alleen discrete geluidssignalen geven in intervallen. Geen extra visuele meldingen die alarm veroorzaken. Dit is een ingebouwde buffer die je uren geeft om op een simpele vergeten moment te reageren.",
        emergencyPlan: "Het noodplan in werking.",
        emergencyPlanText: "Alleen na een lange periode van geen respons, een duur die je zelf bepaalt, wordt het noodplan geactiveerd.",
        familyFriends: "Voor familie en vrienden: Gedeelde gemoedsrust",
        para7: "Ben je een zoon, dochter of kleinkind die zich zorgen maakt over een ouder of grootouder die alleen woont? \"I'm OK\" biedt een niet-storende manier om ervoor te zorgen dat zij veilig zijn. Het biedt je veiligheidsgevoel zonder hun gekoesterde onafhankelijkheid te verstoren. Door hen te helpen de app in te stellen, weet je dat een betrouwbaar systeem op zijn plaats staat om over hen te waken wanneer jij dat niet kunt.",
        howDoesWork: "Hoe werkt de I'm OK app?",
        howDoesWorkText: "De I'm OK app is ontworpen om je veiligheid te waarborgen door je dagelijks op een ingesteld moment in te checken. Als je niet op tijd bevestigt, kan de app je contacten automatisch informeren.",
        settingUpCheckin: "Het dagelijkse inchecken instellen",
        setupText: "Ga naar \"Noodplan\" om de app in te stellen. Hier kun je het volgende instellen:",
        checkinTime: "Inchecktijd:",
        checkinTimeText: "Kies het moment waarop je dagelijks een melding wilt ontvangen om te bevestigen dat je oké bent.",
        yourName: "Je naam:",
        yourNameText: "Voer je naam in. Deze naam wordt gebruikt in de berichten die naar je contacten worden verzonden.",
        emergencyPlanSetup: "Noodplan:",
        emergencyPlanSetupText: "Maak een noodplan dat in de berichten zal worden opgenomen. Hier kun je instructies geven zoals \"bel eerst mijn mobiel, kom dan langs, en bel dan de hulpdiensten\".",
        settingUpActions: "Acties instellen",
        actionsText: "In de sectie \"Acties\" van de instellingen kun je bepalen wie een bericht ontvangt als je niet op het inchecken reageert. Je kunt kiezen tussen SMS en e-mail. Stel de vertraging in (in uren en minuten) waarna het bericht moet worden verzonden. Je kunt meerdere acties toevoegen.",
        smartApproach: "Een slimme aanpak voor het instellen van vertragingen",
        smartApproachText: "Het doel van deze app is om iemand in geval van nood te waarschuwen, niet om onnodig bezorgde berichten te versturen. Het is cruciaal om je vertragingen zorgvuldig in te stellen om een veiligheidsbuffer in te bouwen. Geef jezelf voldoende tijd om je status te bevestigen, zelfs als je je telefoon thuis bent vergeten of anderszins vertraagd bent.",
        layeredApproach: "Overweeg een gelaagde aanpak voor je noodplan. Bijvoorbeeld:",
        firstDelay: "Eerste vertraging (bijv. 12 uur na het inchecken):",
        firstDelayText: "Stel een dichte buur in voor een snelle veiligheidscontrole.",
        secondDelay: "Tweede vertraging (bijv. 18 uur):",
        secondDelayText: "Waarschuw een familielid dat verder weg woont.",
        thirdDelay: "Derde vertraging (bijv. 24 uur):",
        thirdDelayText: "Bel de hulpdiensten als laatste stap.",
        missedCheckin: "Wat gebeurt er als je een inchecken mist?",
        missedCheckinText: "Als je je dagelijkse inchecken mist, wordt het alarmsysteem van de app geactiveerd. De app zal ieder uur een hoorbare herinnering afspelen en zal dit blijven doen tot je bevestigt dat je oké bent.",
        crucially: "Cruciaal is dat er geen acties worden verzonden als je je status bevestigt voordat de vertraging van je eerste actie is verstreken. Het systeem is ontworpen om je voldoende tijd te geven om te reageren en valse alarmen te vermijden.",
        confirmText: "Als je niet bevestigt binnen de ingestelde tijd, zal de app je vooraf bepaalde acties uitvoeren. Je contacten zullen dan de berichten ontvangen die je hebt voorbereid, inclusief je noodplan.",
        dataStorage: "Gegevensopslag",
        dataStorageText: "Alle gegevens die je in de I'm OK app invoert, worden uitsluitend lokaal op je apparaat opgeslagen. De app vereist geen internetverbinding voor de kernfunctionaliteiten en stuurt je persoonlijke gegevens nergens naartoe. De opgeslagen gegevens zijn:",
        settings: "Instellingen:",
        settingsText: "Je naam, de inchecktijd, je noodplan en de geconfigureerde acties (SMS/e-mail) worden lokaal opgeslagen.",
        statusInfo: "Statusinformatie:",
        statusInfoText: "De app volgt lokaal bij wanneer het laatste succesvolle inchecken was en of er meldingen zijn gemist.",
        requiredPermissions: "Vereiste toestemmingen",
        requiredPermissionsText: "Om correct te functioneren vereist de I'm OK-app de volgende toestemmingen:",
        notifications: "Meldingen (POST_NOTIFICATIONS):",
        notificationsText: "Nodig om je dagelijks inchecken herinneringen te sturen.",
        alarms: "Alarmen en herinneringen (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Gebruikt om ervoor te zorgen dat de incheckmededeling op het exacte ingestelde moment wordt bezorgd, zelfs als het apparaat inactief is.",
        sms: "SMS-berichten verzenden (SEND_SMS):",
        smsText: "Stelt de app in staat om een SMS namens jou naar je contacten te sturen als je een inchecken mist.",
        readContacts: "Contacten lezen (READ_CONTACTS):",
        readContactsText: "Stelt je in staat om een ontvanger voor een actie rechtstreeks uit je contactlijst te selecteren. De app leest alleen de geselecteerde contactgegevens en slaat deze niet voor andere doeleinden op.",
        foreground: "Voorgrondservice (FOREGROUND_SERVICE):",
        foregroundText: "Zorgt ervoor dat de app acties op betrouwbare wijze kan uitvoeren (zoals het verzenden van een SMS of e-mail), zelfs wanneer de app op de achtergrond wordt uitgevoerd.",
        inAppPurchases: "In-app aankopen (BILLING):",
        inAppPurchasesText: "Stelt je in staat donaties te doen ter ondersteuning van de app-ontwikkeling.",
        preventPhone: "Telefoon voorkomen van slapen (WAKE_LOCK):",
        preventPhoneText: "Zorgt ervoor dat de app acties op betrouwbare wijze kan uitvoeren (zoals het verzenden van een SMS of e-mail), zelfs wanneer het apparaat in de slaapstand staat.",
        runOnStartup: "Bij opstarten uitvoeren (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Stelt de app in staat automatisch te starten wanneer je apparaat wordt ingeschakeld.",
        contactRequests: "Contact & Verzoeken:",
        developedBy: "Ontwikkeld door:",
        aspiesApps: "Aspie's Apps",
        feedback: "Vragen of feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Met zorg voor mensen en hun huisdieren.",
        whyThisApp: "Waarom deze app?",
        howToUse: "Hoe te gebruiken?",
        privacyPermissions: "Privacy & Permissies:",
        withCare: "Met zorg voor mensen en hun huisdieren.",
    },
    fr: {
        why: "Pourquoi cette app?",
        how: "Comment l'utiliser?",
        privacy: "Confidentialité & Autorisations.",
        contact: "Contact & Demandes.",
        donate: "Donner",
        tagline: "Un filet de sécurité autonome pour vous et vos animaux de compagnie.",
        downloadBtn: "Télécharger sur Google Play",
        coreIdea: "L'idée centrale : Indépendance, sécurisée",
        para1: "Vivre seul s'accompagne d'une inquiétude persistante et silencieuse : \"Et si quelque chose m'arrivait ? Combien de temps faudrait-il avant que quelqu'un ne le sache ?\" Pour ceux qui chérissent leur indépendance mais reconnaissent la réalité de vivre seul, cette question mérite une réponse simple, fiable et privée.",
        para2: "I'm OK est votre filet de sécurité personnel et automatisé. C'est un outil honnête pour la tranquillité d'esprit. Ce n'est pas un suivi ; il respecte votre vie privée tout en veillant discrètement sur votre bien-être. Il est conçu pour l'esprit indépendant qui souhaite soulager ses proches de leurs inquiétudes, sans sacrifier son autonomie.",
        para3: "Chaque jour, à une heure de votre choix, l'application vous envoie une seule notification discrète. Un simple appui sur le bouton \"Je vais bien\" suffit à confirmer votre bien-être. Si cette confirmation ne se produit pas, et seulement alors, votre plan d'urgence personnel et préétabli entre en action.",
        personalStory: "Une histoire personnelle : Pourquoi",
        para4: "\"J'ai développé cette application à partir d'un besoin personnel. En tant que personne vivant seule avec des contacts sociaux limités, ma plus grande préoccupation n'était pas pour moi, mais pour ma petite chienne, Mara. Elle est la raison pour laquelle je sors, la raison pour laquelle cette application existe : pour m'assurer qu'elle ne serait jamais abandonnée seule.",
        para5: "Je suis une de ces personnes dont on parle parfois dans le journal, trouvées dans leur maison des mois plus tard. Le fait que je sois trouvé dans cet état n'est pas mon problème à ce moment. Mais m'assurer que mon chien soit secouru, c'est important. Cette application est la réponse à cette question. C'est ma façon de lui rendre la pareille. Elle me garde en vie, et je construis un système qui garantit sa sécurité.",
        para6: "C'est un outil conçu pour fournir un filet de sécurité, non seulement pour moi, mais pour toute personne dans une situation similaire. C'est un moyen de s'assurer que en cas d'urgence, l'aide est en route pour ceux qui dépendent de nous, qu'ils aient deux jambes ou quatre.\"",
        howItWorks: "Comment cela fonctionne : Le système en trois étapes",
        philosophy: "La philosophie d'I'm OK est la fiabilité et l'évitement des fausses alarmes. Ce n'est pas construit pour la vitesse, mais pour la certitude.",
        dailyCheckin: "L'enregistrement quotidien.",
        dailyCheckinText: "Vous choisissez un moment fixe dans votre journée, peut-être avec votre café du matin. Vous recevez une seule notification. Un simple appui sur \"Je vais bien\" suffit. L'application disparaît alors en arrière-plan.",
        audibleReminder: "Le rappel audible.",
        audibleReminderText: "Vous avez manqué la première notification ? Ne vous inquiétez pas. L'application sait que les gens oublient leurs téléphones. Après la première heure, elle ne produira que des signaux sonores discrets à intervalles. Pas de notifications visuelles supplémentaires pour causer d'alarme. C'est un tampon intégré qui vous donne des heures pour réagir à un simple oubli.",
        emergencyPlan: "Le plan d'urgence en action.",
        emergencyPlanText: "Ce n'est qu'après une longue période d'absence de réponse, une durée que vous contrôlez, que le plan d'urgence s'active.",
        familyFriends: "Pour la famille et les amis : Tranquillité d'esprit partagée",
        para7: "Êtes-vous un fils, une fille ou un petit-enfant inquiet pour un parent ou grand-parent vivant seul ? \"Je vais bien\" offre un moyen non-intrusif de vous assurer qu'ils vont bien. Cela vous offre un sentiment de sécurité sans déranger leur indépendance chérie. En les aidant à configurer l'application, vous saurez qu'un système fiable est en place pour veiller sur eux quand vous ne pouvez pas.",
        howDoesWork: "Comment fonctionne l'application I'm OK?",
        howDoesWorkText: "L'application I'm OK est conçue pour assurer votre sécurité en vous enregistrant quotidiennement à une heure définie. Si vous ne confirmez pas à temps, l'application peut automatiquement informer vos contacts.",
        settingUpCheckin: "Configuration de l'enregistrement quotidien",
        setupText: "Allez à \"Plan d'urgence\" pour configurer l'application. Voici ce que vous pouvez définir :",
        checkinTime: "Heure d'enregistrement:",
        checkinTimeText: "Choisissez l'heure à laquelle vous souhaitez recevoir une notification quotidienne pour confirmer que vous allez bien.",
        yourName: "Votre nom:",
        yourNameText: "Entrez votre nom. Ce nom est utilisé dans les messages envoyés à vos contacts.",
        emergencyPlanSetup: "Plan d'urgence:",
        emergencyPlanSetupText: "Créez un plan d'urgence qui sera inclus dans les messages. Ici, vous pouvez fournir des instructions telles que \"d'abord appeler mon mobile, puis venir, puis appeler les services d'urgence\".",
        settingUpActions: "Configuration des actions",
        actionsText: "Dans la section \"Actions\" des paramètres, vous pouvez définir qui doit recevoir un message si vous ne répondez pas à l'enregistrement. Vous pouvez choisir entre SMS et e-mail. Définissez le délai (en heures et minutes) après lequel le message doit être envoyé. Vous pouvez ajouter plusieurs actions.",
        smartApproach: "Une approche intelligente pour définir les délais",
        smartApproachText: "L'objectif de cette application est d'alerter quelqu'un en cas d'urgence réelle, pas d'envoyer des messages inquiétants inutilement. Il est crucial de définir vos délais avec soin pour créer un tampon de sécurité. Accordez-vous suffisamment de temps pour confirmer votre statut, même si vous avez oublié votre téléphone à la maison ou êtes autrement retardé.",
        layeredApproach: "Considérez une approche en couches pour votre plan d'urgence. Par exemple :",
        firstDelay: "Premier délai (par exemple, 12 heures après l'enregistrement):",
        firstDelayText: "Notifiez un voisin proche pour une vérification rapide du bien-être.",
        secondDelay: "Deuxième délai (par exemple, 18 heures):",
        secondDelayText: "Alertez un membre de la famille qui vit plus loin.",
        thirdDelay: "Troisième délai (par exemple, 24 heures):",
        thirdDelayText: "Contactez les services d'urgence comme dernière étape.",
        missedCheckin: "Que se passe-t-il si vous manquez un enregistrement?",
        missedCheckinText: "Si vous manquez votre enregistrement quotidien, le système d'alerte de l'application s'active. L'application commencera à jouer un rappel audible chaque heure et continuera jusqu'à ce que vous confirmiez que vous allez bien.",
        crucially: "Il est crucial que no actions ne soient envoyées si vous confirmez votre statut avant l'expiration du délai de votre première action. Le système est conçu pour vous donner amplement de temps pour réagir et éviter les fausses alarmes.",
        confirmText: "Si vous ne confirmez pas dans le délai configuré, l'application procédera à l'exécution de vos actions prédéfinies. Vos contacts recevront alors les messages que vous avez préparés, y compris votre plan d'urgence.",
        dataStorage: "Stockage des données",
        dataStorageText: "Toutes les données que vous entrez dans l'application I'm OK sont stockées exclusivement localement sur votre appareil. L'application ne nécessite pas de connexion Internet pour ses fonctionnalités principales et n'envoie vos données personnelles nulle part. Les données stockées incluent :",
        settings: "Paramètres:",
        settingsText: "Votre nom, l'heure d'enregistrement, votre plan d'urgence et les actions configurées (SMS/e-mail) sont stockés localement.",
        statusInfo: "Informations de statut:",
        statusInfoText: "L'application suit localement quand le dernier enregistrement réussi a eu lieu et si des notifications ont été manquées.",
        requiredPermissions: "Autorisations requises",
        requiredPermissionsText: "Pour fonctionner correctement, l'application I'm OK nécessite les autorisations suivantes :",
        notifications: "Notifications (POST_NOTIFICATIONS):",
        notificationsText: "Nécessaire pour vous envoyer le rappel d'enregistrement quotidien.",
        alarms: "Alarmes et rappels (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Utilisé pour s'assurer que la notification d'enregistrement est délivrée à l'heure exacte définie, même si l'appareil est inactif.",
        sms: "Envoyer des messages SMS (SEND_SMS):",
        smsText: "Permet à l'application d'envoyer un SMS en votre nom à vos contacts si vous manquez un enregistrement.",
        readContacts: "Lire les contacts (READ_CONTACTS):",
        readContactsText: "Vous permet de sélectionner un destinataire pour une action directement à partir de votre liste de contacts. L'application ne lit que les informations de contact sélectionnées et ne les stocke pas à d'autres fins.",
        foreground: "Service de premier plan (FOREGROUND_SERVICE):",
        foregroundText: "Garantit que l'application peut effectuer de manière fiable des actions (telles que l'envoi d'un SMS ou d'un e-mail), même lorsque l'application s'exécute en arrière-plan.",
        inAppPurchases: "Achats intégrés (BILLING):",
        inAppPurchasesText: "Vous permet de faire des dons pour soutenir le développement de l'application.",
        preventPhone: "Empêcher le téléphone de dormir (WAKE_LOCK):",
        preventPhoneText: "Garantit que l'application peut effectuer de manière fiable des actions (telles que l'envoi d'un SMS ou d'un e-mail), même lorsque l'appareil est en mode veille.",
        runOnStartup: "Exécuter au démarrage (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Permet à l'application de démarrer automatiquement lorsque votre appareil est allumé.",
        contactRequests: "Contact & Demandes:",
        developedBy: "Développé par:",
        aspiesApps: "Aspie's Apps",
        feedback: "Questions ou commentaires?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Avec soin pour les gens et leurs animaux de compagnie.",
        whyThisApp: "Pourquoi cette application?",
        howToUse: "Comment utiliser?",
        privacyPermissions: "Confidentialité et permissions:",
        withCare: "Avec soin pour les gens et leurs animaux de compagnie.",
    },
    de: {
        why: "Warum diese App?",
        how: "Wie man es benutzt?",
        privacy: "Datenschutz & Genehmigungen.",
        contact: "Kontakt & Anfragen.",
        donate: "Spenden",
        tagline: "Ein autonomes Sicherheitsnetz für Sie und Ihre Haustiere.",
        downloadBtn: "Im Google Play Store erhältlich",
        coreIdea: "Die Kernidee: Unabhängigkeit, gesichert",
        para1: "Allein zu leben bringt eine stille, anhaltende Sorge mit sich: \"Was, wenn mir etwas zustößt? Wie lange würde es dauern, bis jemand es weiß?\" Für diejenigen, die ihre Unabhängigkeit schätzen, aber die Realität des Alleinlebens anerkennen, verdient diese Frage eine einfache, zuverlässige und private Antwort.",
        para2: "I'm OK ist Ihr persönliches, automatisches Sicherheitsnetz. Es ist ein ehrliches Werkzeug für Seelenfrieden. Es ist kein Tracker; es respektiert Ihre Privatsphäre, während es diskret über Ihr Wohlbefinden wacht. Es ist für den unabhängigen Geist konzipiert, der seine Angehörigen von Sorgen befreien möchte, ohne seine Autonomie zu opfern.",
        para3: "Jeden Tag, zu einer Zeit Ihrer Wahl, sendet Ihnen die App eine einzige diskrete Benachrichtigung. Ein einfaches Antippen der Schaltfläche \"Mir geht es gut\" reicht aus, um Ihr Wohlbefinden zu bestätigen. Falls diese Bestätigung nicht erfolgt, und nur dann, wird Ihr persönlicher, vordefinierter Notfallplan in Kraft gesetzt.",
        personalStory: "Eine persönliche Geschichte: Warum",
        para4: "\"Ich habe diese App aus persönlichem Bedarf entwickelt. Als jemand, der allein lebt und begrenzte soziale Kontakte hat, war meine größte Sorge nicht für mich, sondern für meine kleine Hündin Mara. Sie ist der Grund, warum ich nach draußen gehe, der Grund, warum diese App existiert: um sicherzustellen, dass sie nie allein gelassen würde.",
        para5: "Ich bin einer dieser Menschen, über die man manchmal in der Zeitung liest, Monate später in ihrem Haus gefunden. Ob ich in diesem Zustand gefunden werde, ist in diesem Moment mein Problem nicht. Aber sicherzustellen, dass mein Hund gerettet wird, das ist es. Diese App ist die Antwort auf diese Frage. Es ist meine Weise, es ihr zurückzugeben. Sie hält mich am Leben, und ich baue ein System, das ihre Sicherheit garantiert.",
        para6: "Es ist ein Werkzeug, das entwickelt wurde, um nicht nur für mich, sondern für jeden in einer ähnlichen Situation ein Sicherheitsnetz zu bieten. Es ist eine Möglichkeit, sicherzustellen, dass im Notfall Hilfe für diejenigen unterwegs ist, die von uns abhängen, ob sie zwei Beine oder vier haben.\"",
        howItWorks: "So funktioniert es: Das dreistufige System",
        philosophy: "Die Philosophie von I'm OK ist Zuverlässigkeit und die Vermeidung von Fehlalarmen. Sie ist nicht für Geschwindigkeit, sondern für Sicherheit konzipiert.",
        dailyCheckin: "Das tägliche Einchecken.",
        dailyCheckinText: "Sie wählen einen festen Moment in Ihrem Tag, vielleicht mit Ihrem Morgenkaffee. Sie erhalten eine einzige Benachrichtigung. Ein einfaches Antippen von \"Mir geht es gut\" reicht aus. Die App verschwindet dann im Hintergrund.",
        audibleReminder: "Die hörbaren Erinnerung.",
        audibleReminderText: "Haben Sie die erste Benachrichtigung verpasst? Machen Sie sich keine Sorgen. Die App weiß, dass Menschen ihre Telefone vergessen. Nach der ersten Stunde erzeugt sie nur noch diskrete Tonsignale in Intervallen. Keine zusätzlichen visuellen Benachrichtigungen, die Alarm verursachen. Dies ist ein eingebauter Puffer, der Ihnen Stunden gibt, um auf ein einfaches Versehen zu reagieren.",
        emergencyPlan: "Der Notfallplan in Aktion.",
        emergencyPlanText: "Nur nach einer langen Zeit ohne Reaktion, einer Dauer, die Sie kontrollieren, wird der Notfallplan aktiviert.",
        familyFriends: "Für Familie und Freunde: Gemeinsame Sicherheit",
        para7: "Sind Sie ein Sohn, eine Tochter oder ein Enkel, der sich um einen Elternteil oder Großelternteil sorgt, der allein lebt? \"Mir geht es gut\" bietet eine nicht-aufdringliche Möglichkeit, ihre Sicherheit zu gewährleisten. Es bietet Ihnen ein Sicherheitsgefühl, ohne ihre geschätzte Unabhängigkeit zu stören. Indem Sie ihnen helfen, die App einzurichten, wissen Sie, dass ein zuverlässiges System vorhanden ist, das über sie wacht, wenn Sie es nicht können.",
        howDoesWork: "Wie funktioniert die I'm OK App?",
        howDoesWorkText: "Die I'm OK App soll Ihre Sicherheit gewährleisten, indem Sie täglich zu einer festgelegten Zeit eingecheckt werden. Wenn Sie nicht rechtzeitig bestätigen, kann die App Ihre Kontakte automatisch informieren.",
        settingUpCheckin: "Einrichten des täglichen Eincheckens",
        setupText: "Gehen Sie zu \"Notfallplan\", um die App zu konfigurieren. Hier können Sie Folgendes einstellen:",
        checkinTime: "Einchecken-Zeit:",
        checkinTimeText: "Wählen Sie die Zeit, zu der Sie täglich eine Benachrichtigung erhalten möchten, um zu bestätigen, dass es Ihnen gut geht.",
        yourName: "Dein Name:",
        yourNameText: "Geben Sie Ihren Namen ein. Dieser Name wird in den Nachrichten verwendet, die an Ihre Kontakte gesendet werden.",
        emergencyPlanSetup: "Notfallplan:",
        emergencyPlanSetupText: "Erstellen Sie einen Notfallplan, der in den Nachrichten enthalten sein soll. Hier können Sie Anweisungen wie \"rufen Sie zuerst mein Mobiltelefon an, kommen Sie dann vorbei und rufen Sie dann den Notfalldienst an\" geben.",
        settingUpActions: "Einrichten von Aktionen",
        actionsText: "Im Abschnitt \"Aktionen\" der Einstellungen können Sie definieren, wer eine Nachricht erhalten soll, wenn Sie nicht auf das Einchecken reagieren. Sie können zwischen SMS und E-Mail wählen. Legen Sie die Verzögerung (in Stunden und Minuten) fest, nach der die Nachricht gesendet werden soll. Sie können mehrere Aktionen hinzufügen.",
        smartApproach: "Ein intelligenter Ansatz zum Einstellen von Verzögerungen",
        smartApproachText: "Der Zweck dieser App besteht darin, jemanden in einem echten Notfall zu warnen, nicht um unnötig besorgte Nachrichten zu versenden. Es ist entscheidend, Ihre Verzögerungen sorgfältig einzustellen, um einen Sicherheitspuffer zu schaffen. Geben Sie sich selbst genug Zeit, um Ihren Status zu bestätigen, auch wenn Sie Ihr Telefon zu Hause vergessen haben oder anderweitig verspätet sind.",
        layeredApproach: "Erwägen Sie einen gestuften Ansatz für Ihren Notfallplan. Zum Beispiel:",
        firstDelay: "Erste Verzögerung (z. B. 12 Stunden nach dem Einchecken):",
        firstDelayText: "Benachrichtigen Sie einen nahen Nachbarn für eine schnelle Wellness-Überprüfung.",
        secondDelay: "Zweite Verzögerung (z. B. 18 Stunden):",
        secondDelayText: "Warnen Sie ein Familienmitglied, das weiter weg wohnt.",
        thirdDelay: "Dritte Verzögerung (z. B. 24 Stunden):",
        thirdDelayText: "Kontaktieren Sie als letzten Schritt den Notfalldienst.",
        missedCheckin: "Was passiert, wenn Sie ein Einchecken verpassen?",
        missedCheckinText: "Wenn Sie Ihr tägliches Einchecken verpassen, wird das Alarmsystem der App aktiviert. Die App beginnt dann, jede Stunde eine hörbare Erinnerung abzuspielen, und setzt dies fort, bis Sie bestätigen, dass es Ihnen gut geht.",
        crucially: "Es ist entscheidend, dass keine Aktionen gesendet werden, wenn Sie Ihren Status bestätigen, bevor die Verzögerung Ihrer ersten Aktion abgelaufen ist. Das System soll Ihnen viel Zeit zum Reagieren geben und Fehlalarme vermeiden.",
        confirmText: "Wenn Sie nicht innerhalb der konfigurierten Zeit bestätigen, führt die App Ihre vordefinierten Aktionen aus. Ihre Kontakte erhalten dann die Nachrichten, die Sie vorbereitet haben, einschließlich Ihres Notfallplans.",
        dataStorage: "Datenspeicherung",
        dataStorageText: "Alle Daten, die Sie in der I'm OK App eingeben, werden ausschließlich lokal auf Ihrem Gerät gespeichert. Die App erfordert keine Internetverbindung für ihre Kernfunktionalität und sendet Ihre persönlichen Daten nirgendwo hin. Die gespeicherten Daten umfassen:",
        settings: "Einstellungen:",
        settingsText: "Ihr Name, die Einchecken-Zeit, Ihr Notfallplan und die konfigurierten Aktionen (SMS/E-Mail) werden lokal gespeichert.",
        statusInfo: "Statusinformationen:",
        statusInfoText: "Die App verfolgt lokal, wann das letzte erfolgreiche Einchecken erfolgte und ob Benachrichtigungen verpasst wurden.",
        requiredPermissions: "Erforderliche Genehmigungen",
        requiredPermissionsText: "Damit die App korrekt funktioniert, benötigt die I'm OK-App die folgenden Berechtigungen:",
        notifications: "Benachrichtigungen (POST_NOTIFICATIONS):",
        notificationsText: "Erforderlich, um Ihnen die tägliche Einchecken-Erinnerung zu senden.",
        alarms: "Alarme und Erinnerungen (SCHEDULE_EXACT_ALARM):",
        alarmsText: "Wird verwendet, um sicherzustellen, dass die Einchecken-Benachrichtigung zur exakt eingestellten Zeit zugestellt wird, auch wenn das Gerät inaktiv ist.",
        inAppPurchases: "In-App-Käufe (BILLING):",
        inAppPurchasesText: "Ermöglicht es Ihnen, Spenden zur Unterstützung der App-Entwicklung zu tätigen.",
        preventPhone: "Telefon am Schlafen hindern (WAKE_LOCK):",
        preventPhoneText: "Stellt sicher, dass die App Aktionen zuverlässig ausführen kann (wie das Senden einer SMS oder E-Mail), auch wenn sich das Gerät im Schlafmodus befindet.",
        runOnStartup: "Beim Start ausführen (RECEIVE_BOOT_COMPLETED):",
        runOnStartupText: "Ermöglicht der App, automatisch zu starten, wenn Ihr Gerät eingeschaltet wird.",
        sms: "SMS-Nachrichten senden (SEND_SMS):",
        smsText: "Ermöglicht der App, an Ihrer Stelle eine SMS an Ihre Kontakte zu senden, wenn Sie ein Einchecken verpassen.",
        readContacts: "Kontakte lesen (READ_CONTACTS):",
        readContactsText: "Ermöglicht es Ihnen, einen Empfänger für eine Aktion direkt aus Ihrer Kontaktliste auszuwählen. Die App liest nur die ausgewählten Kontaktinformationen und speichert sie nicht für andere Zwecke.",
        foreground: "Vordergrund-Service (FOREGROUND_SERVICE):",
        foregroundText: "Stellt sicher, dass die App Aktionen zuverlässig ausführen kann (wie das Senden einer SMS oder E-Mail), auch wenn die App im Hintergrund ausgeführt wird.",
        contactRequests: "Kontakt & Anfragen:",
        developedBy: "Entwickelt von:",
        aspiesApps: "Aspie's Apps",
        feedback: "Fragen oder Feedback?",
        email: "aspies.apps@gmail.com",
        footerText: "&copy; 2026 imok.be | Mit Sorgfalt für Menschen und ihre Haustiere.",
        whyThisApp: "Warum diese App?",
        howToUse: "Wie man es benutzt?",
        privacyPermissions: "Datenschutz & Berechtigungen:",
        withCare: "Mit Sorgfalt für Menschen und ihre Haustiere.",
    }
};

function changeLanguage(lang) {
    localStorage.setItem('language', lang);
    updatePageLanguage(lang);
}

function updatePageLanguage(lang) {
    const trans = translations[lang] || translations.en;
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (trans[key]) {
            if (element.id === 'footer-text') {
                element.innerHTML = trans[key];
            } else {
                element.textContent = trans[key];
            }
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('language') || 'en';
    document.getElementById('language-select').value = savedLang;
    updatePageLanguage(savedLang);
});